//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Input/HeroInputAction.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @HeroInputAction : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @HeroInputAction()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""HeroInputAction"",
    ""maps"": [
        {
            ""name"": ""Hero"",
            ""id"": ""f8634568-62dd-4072-9d4a-855e4192d135"",
            ""actions"": [
                {
                    ""name"": ""controls_movement_label"",
                    ""type"": ""Value"",
                    ""id"": ""2bad78ee-02fb-40f2-bed5-44f0701b23fb"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""controls_saySomething_label"",
                    ""type"": ""Button"",
                    ""id"": ""08adf8a7-131e-43f2-a72c-72d27d67448e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""controls_interact_label"",
                    ""type"": ""Button"",
                    ""id"": ""e3fa6102-e5ee-440f-9923-d749e91f3e87"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""controls_attack_label"",
                    ""type"": ""Button"",
                    ""id"": ""27d0cfa6-906f-4486-83a7-680e881e04b7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""controls_useInventory_label"",
                    ""type"": ""Button"",
                    ""id"": ""d2b91769-32e9-4ad3-840b-8bd01b6bf147"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""controls_nextItem_label"",
                    ""type"": ""Button"",
                    ""id"": ""813e6277-69e1-4721-a3c2-5e0d6d973312"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""controls_menu_label"",
                    ""type"": ""Button"",
                    ""id"": ""22b1c505-31fb-4e9a-b671-af0237079901"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""controls_candle_label"",
                    ""type"": ""Button"",
                    ""id"": ""a6142a40-bdfb-4cd7-91d0-11256984119b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""Keyboard"",
                    ""id"": ""c6813d21-8781-4fc3-8732-63e153b3169f"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""controls_movement_label"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Up"",
                    ""id"": ""86db51ee-df9c-4578-a0bf-dc032f0de791"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""controls_movement_label"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Down"",
                    ""id"": ""b0b05edf-6e84-4988-b364-723b56c6ac82"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""controls_movement_label"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Left"",
                    ""id"": ""ab3ed4c6-7334-4fd0-b3d4-7104bb70ffe5"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""controls_movement_label"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Right"",
                    ""id"": ""13038c7c-5dd4-4e4d-9cd0-b3a03b656398"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""controls_movement_label"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Arrows"",
                    ""id"": ""bdfc7309-d6f9-4dda-a172-dc429d604f0c"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""controls_movement_label"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Up"",
                    ""id"": ""65f32f1a-1981-4c88-be73-ae9174542f9b"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""controls_movement_label"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Down"",
                    ""id"": ""c5338aeb-8630-479a-9527-f3a545315848"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""controls_movement_label"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Left"",
                    ""id"": ""38b34072-0f3c-4070-b440-e2b8a9a66da2"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""controls_movement_label"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Right"",
                    ""id"": ""a0e54734-f27e-43ec-82a0-d835495bc109"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""controls_movement_label"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""733bd1f0-5042-409d-844f-61a0d617d971"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""controls_saySomething_label"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""61a3bacd-ffbc-4fd8-8a92-f110ba0aa10b"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""controls_interact_label"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7823b8b7-5dbc-4463-b484-2a0ad05ca8cd"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""controls_attack_label"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cc9ac055-fd61-44aa-861f-d583cb839e68"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": ""Hold(duration=1),Press(behavior=1)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""controls_useInventory_label"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""349856d6-b302-4660-8951-1791f6a0e9c9"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""controls_nextItem_label"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d5f89e89-5f85-4e06-9530-ecdfe107f0ca"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""controls_menu_label"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d153e37c-a8d7-4602-a2e9-c7b6dcb4077e"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""controls_candle_label"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Hero
        m_Hero = asset.FindActionMap("Hero", throwIfNotFound: true);
        m_Hero_controls_movement_label = m_Hero.FindAction("controls_movement_label", throwIfNotFound: true);
        m_Hero_controls_saySomething_label = m_Hero.FindAction("controls_saySomething_label", throwIfNotFound: true);
        m_Hero_controls_interact_label = m_Hero.FindAction("controls_interact_label", throwIfNotFound: true);
        m_Hero_controls_attack_label = m_Hero.FindAction("controls_attack_label", throwIfNotFound: true);
        m_Hero_controls_useInventory_label = m_Hero.FindAction("controls_useInventory_label", throwIfNotFound: true);
        m_Hero_controls_nextItem_label = m_Hero.FindAction("controls_nextItem_label", throwIfNotFound: true);
        m_Hero_controls_menu_label = m_Hero.FindAction("controls_menu_label", throwIfNotFound: true);
        m_Hero_controls_candle_label = m_Hero.FindAction("controls_candle_label", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Hero
    private readonly InputActionMap m_Hero;
    private IHeroActions m_HeroActionsCallbackInterface;
    private readonly InputAction m_Hero_controls_movement_label;
    private readonly InputAction m_Hero_controls_saySomething_label;
    private readonly InputAction m_Hero_controls_interact_label;
    private readonly InputAction m_Hero_controls_attack_label;
    private readonly InputAction m_Hero_controls_useInventory_label;
    private readonly InputAction m_Hero_controls_nextItem_label;
    private readonly InputAction m_Hero_controls_menu_label;
    private readonly InputAction m_Hero_controls_candle_label;
    public struct HeroActions
    {
        private @HeroInputAction m_Wrapper;
        public HeroActions(@HeroInputAction wrapper) { m_Wrapper = wrapper; }
        public InputAction @controls_movement_label => m_Wrapper.m_Hero_controls_movement_label;
        public InputAction @controls_saySomething_label => m_Wrapper.m_Hero_controls_saySomething_label;
        public InputAction @controls_interact_label => m_Wrapper.m_Hero_controls_interact_label;
        public InputAction @controls_attack_label => m_Wrapper.m_Hero_controls_attack_label;
        public InputAction @controls_useInventory_label => m_Wrapper.m_Hero_controls_useInventory_label;
        public InputAction @controls_nextItem_label => m_Wrapper.m_Hero_controls_nextItem_label;
        public InputAction @controls_menu_label => m_Wrapper.m_Hero_controls_menu_label;
        public InputAction @controls_candle_label => m_Wrapper.m_Hero_controls_candle_label;
        public InputActionMap Get() { return m_Wrapper.m_Hero; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(HeroActions set) { return set.Get(); }
        public void SetCallbacks(IHeroActions instance)
        {
            if (m_Wrapper.m_HeroActionsCallbackInterface != null)
            {
                @controls_movement_label.started -= m_Wrapper.m_HeroActionsCallbackInterface.OnControls_movement_label;
                @controls_movement_label.performed -= m_Wrapper.m_HeroActionsCallbackInterface.OnControls_movement_label;
                @controls_movement_label.canceled -= m_Wrapper.m_HeroActionsCallbackInterface.OnControls_movement_label;
                @controls_saySomething_label.started -= m_Wrapper.m_HeroActionsCallbackInterface.OnControls_saySomething_label;
                @controls_saySomething_label.performed -= m_Wrapper.m_HeroActionsCallbackInterface.OnControls_saySomething_label;
                @controls_saySomething_label.canceled -= m_Wrapper.m_HeroActionsCallbackInterface.OnControls_saySomething_label;
                @controls_interact_label.started -= m_Wrapper.m_HeroActionsCallbackInterface.OnControls_interact_label;
                @controls_interact_label.performed -= m_Wrapper.m_HeroActionsCallbackInterface.OnControls_interact_label;
                @controls_interact_label.canceled -= m_Wrapper.m_HeroActionsCallbackInterface.OnControls_interact_label;
                @controls_attack_label.started -= m_Wrapper.m_HeroActionsCallbackInterface.OnControls_attack_label;
                @controls_attack_label.performed -= m_Wrapper.m_HeroActionsCallbackInterface.OnControls_attack_label;
                @controls_attack_label.canceled -= m_Wrapper.m_HeroActionsCallbackInterface.OnControls_attack_label;
                @controls_useInventory_label.started -= m_Wrapper.m_HeroActionsCallbackInterface.OnControls_useInventory_label;
                @controls_useInventory_label.performed -= m_Wrapper.m_HeroActionsCallbackInterface.OnControls_useInventory_label;
                @controls_useInventory_label.canceled -= m_Wrapper.m_HeroActionsCallbackInterface.OnControls_useInventory_label;
                @controls_nextItem_label.started -= m_Wrapper.m_HeroActionsCallbackInterface.OnControls_nextItem_label;
                @controls_nextItem_label.performed -= m_Wrapper.m_HeroActionsCallbackInterface.OnControls_nextItem_label;
                @controls_nextItem_label.canceled -= m_Wrapper.m_HeroActionsCallbackInterface.OnControls_nextItem_label;
                @controls_menu_label.started -= m_Wrapper.m_HeroActionsCallbackInterface.OnControls_menu_label;
                @controls_menu_label.performed -= m_Wrapper.m_HeroActionsCallbackInterface.OnControls_menu_label;
                @controls_menu_label.canceled -= m_Wrapper.m_HeroActionsCallbackInterface.OnControls_menu_label;
                @controls_candle_label.started -= m_Wrapper.m_HeroActionsCallbackInterface.OnControls_candle_label;
                @controls_candle_label.performed -= m_Wrapper.m_HeroActionsCallbackInterface.OnControls_candle_label;
                @controls_candle_label.canceled -= m_Wrapper.m_HeroActionsCallbackInterface.OnControls_candle_label;
            }
            m_Wrapper.m_HeroActionsCallbackInterface = instance;
            if (instance != null)
            {
                @controls_movement_label.started += instance.OnControls_movement_label;
                @controls_movement_label.performed += instance.OnControls_movement_label;
                @controls_movement_label.canceled += instance.OnControls_movement_label;
                @controls_saySomething_label.started += instance.OnControls_saySomething_label;
                @controls_saySomething_label.performed += instance.OnControls_saySomething_label;
                @controls_saySomething_label.canceled += instance.OnControls_saySomething_label;
                @controls_interact_label.started += instance.OnControls_interact_label;
                @controls_interact_label.performed += instance.OnControls_interact_label;
                @controls_interact_label.canceled += instance.OnControls_interact_label;
                @controls_attack_label.started += instance.OnControls_attack_label;
                @controls_attack_label.performed += instance.OnControls_attack_label;
                @controls_attack_label.canceled += instance.OnControls_attack_label;
                @controls_useInventory_label.started += instance.OnControls_useInventory_label;
                @controls_useInventory_label.performed += instance.OnControls_useInventory_label;
                @controls_useInventory_label.canceled += instance.OnControls_useInventory_label;
                @controls_nextItem_label.started += instance.OnControls_nextItem_label;
                @controls_nextItem_label.performed += instance.OnControls_nextItem_label;
                @controls_nextItem_label.canceled += instance.OnControls_nextItem_label;
                @controls_menu_label.started += instance.OnControls_menu_label;
                @controls_menu_label.performed += instance.OnControls_menu_label;
                @controls_menu_label.canceled += instance.OnControls_menu_label;
                @controls_candle_label.started += instance.OnControls_candle_label;
                @controls_candle_label.performed += instance.OnControls_candle_label;
                @controls_candle_label.canceled += instance.OnControls_candle_label;
            }
        }
    }
    public HeroActions @Hero => new HeroActions(this);
    public interface IHeroActions
    {
        void OnControls_movement_label(InputAction.CallbackContext context);
        void OnControls_saySomething_label(InputAction.CallbackContext context);
        void OnControls_interact_label(InputAction.CallbackContext context);
        void OnControls_attack_label(InputAction.CallbackContext context);
        void OnControls_useInventory_label(InputAction.CallbackContext context);
        void OnControls_nextItem_label(InputAction.CallbackContext context);
        void OnControls_menu_label(InputAction.CallbackContext context);
        void OnControls_candle_label(InputAction.CallbackContext context);
    }
}
